#include<dpp/dpp.h>
#include<dpp/event.h>
#include<algorithm>
#include<fstream>
#include<stdlib.h>
#include<iostream>
#include<string>
#include<time.h>
#include<cmath>
#include<random>
#include<math.h>
#include"additional/bot_token.h"
#include"additional/banchecker.h"